### PR TITLE
Stack operations, Jumps and Subroutines

### PR DESCRIPTION
**Pull request by LaurinZ**
Stack Operations implemented, included in step.rs and tested with simple test.
Jumps and Subroutines added and tested aswell.

### CODE REVIEW

**Review by AnnsAnns — COMMENTED** [review]
I might be wrong but shouldn't you store your registers when switching stacks?

**Comment by AnnsAnns** [comment]
other than that lgtm :+1:

**Comment by LaurinZ** [comment]
> I might be wrong but shouldn't you store your registers when switching stacks?

I have no clue XD

**Comment by AnnsAnns** [comment]
Well, Merge first, cry later 😅

**Pull request merged**
